
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SmartWaste_API.Business.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Address
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Address()
    {

        this.CompanyAddresses = new HashSet<CompanyAddress>();

        this.PersonAddresses = new HashSet<PersonAddress>();

        this.Points = new HashSet<Point>();

    }


    public System.Guid ID { get; set; }

    public string Line1 { get; set; }

    public string Line2 { get; set; }

    public string ZipCode { get; set; }

    public string Neighborhood { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public int CityID { get; set; }



    public virtual City City { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CompanyAddress> CompanyAddresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PersonAddress> PersonAddresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Point> Points { get; set; }

}

}
