//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWaste_API.Business.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartWasteDatabaseConnection : DbContext
    {
        public SmartWasteDatabaseConnection()
            : base("name=SmartWasteDatabaseConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyAddress> CompanyAddress { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceHistory> DeviceHistory { get; set; }
        public virtual DbSet<DeviceStatus> DeviceStatus { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<EmployeeCompanyRequest> EmployeeCompanyRequest { get; set; }
        public virtual DbSet<Identification> Identification { get; set; }
        public virtual DbSet<IdentificationType> IdentificationType { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonAddress> PersonAddress { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<Point> Point { get; set; }
        public virtual DbSet<PointHistory> PointHistory { get; set; }
        public virtual DbSet<PointStatus> PointStatus { get; set; }
        public virtual DbSet<PointType> PointType { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<RouteHistory> RouteHistory { get; set; }
        public virtual DbSet<RoutePoint> RoutePoint { get; set; }
        public virtual DbSet<RouteStatus> RouteStatus { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
