//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWaste_API.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompanyRequest
    {
        public System.Guid ID { get; set; }
        public string Link { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public System.Guid CreatedByID { get; set; }
        public Nullable<System.Guid> PersonID { get; set; }
        public string Email { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
