//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartWaste_API.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Point()
        {
            this.PointHistories = new HashSet<PointHistory>();
            this.RoutePoints = new HashSet<RoutePoint>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid AddressID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.Guid> DeviceID { get; set; }
        public int TypeID { get; set; }
        public int PointRouteStatusID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Device Device { get; set; }
        public virtual PointStatu PointStatu { get; set; }
        public virtual PointType PointType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointHistory> PointHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePoint> RoutePoints { get; set; }
        public virtual PointRouteStatu PointRouteStatu { get; set; }
    }
}
