
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SmartWaste_API.Business.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Route
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Route()
    {

        this.RouteHistories = new HashSet<RouteHistory>();

        this.RoutePoints = new HashSet<RoutePoint>();

    }


    public System.Guid ID { get; set; }

    public Nullable<System.Guid> AssignedTo { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<System.DateTime> ClosedOn { get; set; }

    public int StatusID { get; set; }

    public System.Guid CreatedBy { get; set; }

    public System.Guid CompanyID { get; set; }

    public decimal ExpectedKilometers { get; set; }

    public decimal ExpectedMinutes { get; set; }



    public virtual Company Company { get; set; }

    public virtual Person Person { get; set; }

    public virtual Person Person1 { get; set; }

    public virtual RouteStatu RouteStatu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RouteHistory> RouteHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RoutePoint> RoutePoints { get; set; }

}

}
